// AUTH/USER_LOGIN
export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_COMPLETED = 'USER_LOGIN_COMPLETED';
export const USER_LOGIN_ERROR = 'USER_LOGIN_ERROR';
export const USER_LOGIN_RESET = 'USER_LOGIN_RESET';

// AUTH/USER_REGISTER
export const USER_REGISTER = 'USER_REGISTER';
export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_COMPLETED = 'USER_REGISTER_COMPLETED';
export const USER_REGISTER_ERROR = 'USER_REGISTER_ERROR';

// AUTH/USER_LOGOUT
export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_LOGOUT_REQUEST = 'USER_LOGOUT_REQUEST';
export const USER_LOGOUT_COMPLETED = 'USER_LOGOUT_COMPLETED';
export const USER_LOGOUT_ERROR = 'USER_LOGOUT_ERROR';
